### ISSUE TITLE
Why is object available after close()?

### ISSUE THREAD

**Issue by gebrits** [allenluce/mmap-object#25]
Probably missing something, but following the given [example](https://github.com/allenluce/mmap-object#usage) `new Shared.Open('filename')` is done after `shared_object.close()` is performed. Indeed this works.

I assumed doing `shared_object.close()` would free up the the shared object, thus making it unavailable for `new Shared.Open('filename')` . Why is it still available? 

Underlying question: how can I be sure that objects are removed from memory?

**Comment by allenluce** [comment]
There are a couple levels to what a `Shared` JS object is doing here:

1. On a higher level, it's a wrapper for the *mechanism* to handle shared memory via mmap. The infrastructure for that mechanism is a permanent part of the object and cannot be explicitly deallocated. Accessibility is a function of the scope of the variable but it's up to the garbage collector to deallocate it. In typical use it wont be deallocated until the process exits.

1. Internally, this mechanism hangs onto a mapping to shared memory (as created by `mmap`). The `close()` call removes this mapping so the memory is no longer accessible to the current process. It's up to the operating system to determine how long that memory dwells in residence. If other processes are accessing the same portions of the same `mmap`'d file, they stay resident. Otherwise it's up to the paging policy of the OS as to when it's ejected.

`mmap`'d memory uses a different allocator than non-shared memory (the kind you'd use with `malloc()/free()`) and due to it's nature as a shared memory-mapped filesystem object has very different lifetime semantics.
